	NDefines.NGame.GAME_SPEED_SECONDS = { 2.0, 0.5, 0.2, 0.1, 0.0 } -- game speeds for each level. Must be 5 entries with last one 0 for unbound			-- Minimum number of major countries involved in a war to consider it major enough to not end the game even though the enddate has been reached.
	NDefines.NGame.OIL_RESOURCE= "grain"							-- Name of the oil resource
	NDefines.NGame.FUEL_RESOURCE = "grain"							-- resource that will give country fuel
	NDefines.NGame.ENERGY_RESOURCE = "gold_ingot"						-- resource that will give country energy 					-- maximum allowed iteration for loop effects			-- max recursion for scripted localizations
	
	
	NDefines.NDiplomacy.MAX_TRUST_VALUE = 150							-- Max trust value cap.
	NDefines.NDiplomacy.MIN_TRUST_VALUE = -150							-- Min trust value cap.
	NDefines.NDiplomacy.MAX_OPINION_VALUE = 150						-- Max opinion value cap.
	NDefines.NDiplomacy.MIN_OPINION_VALUE = -150						-- Min opinion value cap.
	NDefines.NDiplomacy.BASE_TRUCE_PERIOD = 60						-- Base truce period in days.
	NDefines.NDiplomacy.TRUCE_PERIOD_AFTER_KICKING_FROM_FACTION = 10				-- Truce period after kicking someone from faction in days.
	NDefines.NDiplomacy.TRUCE_BREAK_COST_PP = 50						-- Base cost in PP of breaking a truce by joining a war or accepting a call to war ( you cannot declare war yourself until the truce if up ), this is then multiplied by the time left on the truce ( so once half the truce is up it only cost 50% of this )
	NDefines.NDiplomacy.BASE_PEACE_PUPPET_FACTOR = 50					-- Base factor for puppet in %.
	NDefines.NDiplomacy.BASE_PEACE_LIBERATE_FACTOR = 40				-- Base factor for liberate in %.
	-- In peace conference, adding a stackable to a peace action, increment the cost by a percentage
	NDefines.NDiplomacy.PEACE_COST_FACTOR_STACK_DEMILITARIZED_ZONE = 0.9
	NDefines.NDiplomacy.PEACE_COST_FACTOR_STACK_WAR_REPARATION = 0.15
	NDefines.NDiplomacy.PEACE_COST_FACTOR_STACK_RESOURCE_RIGHTS = 0.5
	NDefines.NDiplomacy.PEACE_COST_FACTOR_STACK_DISMANTLE_INDUSTRY = 0.9
	-- peace conference can set timed effect, set length in days
	NDefines.NDiplomacy.PEACE_TIMED_EFFECT_LENGTH_DEMILITARIZED_ZONE = 150 -- 5 years
	NDefines.NDiplomacy.PEACE_TIMED_EFFECT_LENGTH_WAR_REPARATION = 250
	NDefines.NDiplomacy.PEACE_TIMED_EFFECT_LENGTH_RESOURCE_RIGHTS = 1960

	-- The Influence cost modifier is basically the inverse of distance. Nearby states are cheaper, and far-away states are more expensive.
	-- We basically do a two-segment lerp:
	--   if distance is between [0, NEUTRAL_DIST], we lerp the cost modifier between [MIN_DIST_COST_MODIFIER, 1.0]
	--   if distance is between [NEUTRAL_DIST, MAX_DIST], we lerp the cost modifier between [1.0, MAX_DIST_COST_MODIFIER]
	-- The below values represent (pixel distance / INFLUENCE_DISTANCE_DIVISOR)
	NDefines.NDiplomacy.NAP_EXPIRY_MONTHS = 28                         -- NAPs expire after this many months
	NDefines.NDiplomacy.NAP_UNBREAKABLE_MONTHS = 2                    -- NAPS cannot be broken for this many months
	NDefines.NDiplomacy.VERY_GOOD_OPINION = 80							-- Threshold for a country that has a very good opinion of you.
	NDefines.NDiplomacy.VERY_BAD_OPINION = -80							-- Threshold for a country that has a very bad opinion of you.
	NDefines.NDiplomacy.TENSION_STATE_VALUE = 0.05						-- Tension value gained by annexing one state (this value used to be divided by 20, this is no longer the case)
	NDefines.NDiplomacy.TENSION_CIVIL_WAR_IMPACT = 0.2					-- civil war multiplier on tension.
	NDefines.NDiplomacy.TENSION_NO_CB_WAR = 14							-- Amount of tension generated by a no-CB wargoal
	NDefines.NDiplomacy.TENSION_CB_WAR = 2							-- Amount of tension generated by a war with a CB
	NDefines.NDiplomacy.TENSION_ANNEX_NO_CLAIM = 0.1					-- Amount of tension generated by annexing a state you don't have claims on
	NDefines.NDiplomacy.TENSION_ANNEX_CLAIM = 0.05						-- Amount of tension generated by annexing a state you DO have claims on						-- Amount of tension generated by annexing a state that is your core
	NDefines.NDiplomacy.TENSION_TIME_SCALE_START_DATE = "14.1.1.12"	-- Starting at this date, the tension values will be scaled down (will be equal to 1 before that)
	NDefines.NDiplomacy.TENSION_FACTION_JOIN = 2
	NDefines.NDiplomacy.TENSION_JOIN_ATTACKER = 1						-- scale of the amount of tension added when country joins attacker side

	NDefines.NCountry.BASE_FUEL_GAIN_PER_OIL = 0.5						-- base amount of fuel gained hourly per excess oil
	NDefines.NCountry.BASE_FUEL_GAIN = 1.0							-- base amount of fuel gained hourly, independent of excess oil
	NDefines.NCountry.BASE_FUEL_CAPACITY = 35000


	NDefines.NProduction.RESOURCE_TO_ENERGY_COEFFICIENT = 9.0		-- How much energy per coal produces
	NDefines.NProduction.BASE_COUNTRY_ENERGY_PRODUCTION = 8.0 			-- The base energy production of a country
	NDefines.NProduction.ENERGY_SCALING_COST_BY_FACTORY_COUNT = 0.0225 -- Scales energy cost based on the total number of factories
	NDefines.NProduction.BASE_ENERGY_COST = 0.2						-- How much energy per factory consumes
	NDefines.NProduction.ENERGY_COST_CAP = 6						-- Maximum energy cost per factory
	NDefines.NProduction.ENERGY_SCALE_PER_TRADE_FACTORY_EXPORT = 0.25 -- Factor of how many of the factories gained from trade is affects the energy cost scaling
	NDefines.NProduction.BASE_FACTORY_SPEED = 1.25 					-- Base factory speed multiplier (how much hoi3 style IC each factory gives).
	NDefines.NProduction.BASE_FACTORY_SPEED_MIL = 1.0 				-- Base factory speed multiplier (how much hoi3 style IC each factory gives).
	NDefines.NProduction.BASE_FACTORY_SPEED_NAV = 0.5			-- Base factory speed multiplier (how much hoi3 style IC each factory gives).
	NDefines.NProduction.BASE_FACTORY_START_EFFICIENCY_FACTOR = 10	-- Base start efficiency for factories expressed in %.
	NDefines.NProduction.POWERED_FACTORY_SPEED = 2 					--Powered factory speed multiplier.
	NDefines.NProduction.POWERED_FACTORY_SPEED_MIL = 2 			--Powered factory speed multiplier.
	NDefines.NProduction.POWERED_FACTORY_SPEED_NAV = 1.5


	NDefines.NMilitary.ATTRITION_EQUIPMENT_LOSS_CHANCE = 0.009		   -- Chance for loosing equipment when suffer attrition. Scaled up the stronger attrition is. Then scaled down by equipment reliability.
	NDefines.NMilitary.ATTRITION_WHILE_MOVING_FACTOR = 1.5
	NDefines.NMilitary.LAND_SPEED_MODIFIER = 0.02                    -- basic speed control
	NDefines.NMilitary.RIVER_CROSSING_PENALTY = -0.4                 -- small river crossing
	NDefines.NMilitary.RIVER_CROSSING_PENALTY_LARGE = -0.6           -- large river crossing
	NDefines.NMilitary.RIVER_CROSSING_SPEED_PENALTY = -0.4           -- small river crossing
	NDefines.NMilitary.RIVER_CROSSING_SPEED_PENALTY_LARGE = -0.6

	NDefines.NMilitary.ARMY_FUEL_COST_MULT = 0.8						-- fuel cost multiplier for all army related stuff
	NDefines.NMilitary.ARMY_COMBAT_FUEL_MULT =   4.0					-- fuel consumption ratio in combat (plus ARMY_MOVEMENT_FUEL_MULT if you are also moving. ie offensive combat)
	NDefines.NMilitary.ARMY_TRAINING_FUEL_MULT = 3.0					-- fuel consumption ratio while training
	NDefines.NMilitary.ARMY_MOVEMENT_FUEL_MULT = 2.0					-- fuel consumption ratio while moving
	NDefines.NMilitary.ARMY_NAVAL_TRANSFER_FUEL_MULT = 0.1			-- fuel consumption ratio while naval transferring
	NDefines.NMilitary.ARMY_STRATEGIC_DEPLOYMENT_FUEL_MULT = 0.1		-- fuel consumption ratio while doing strategic deployment
	NDefines.NMilitary.ARMY_IDLE_FUEL_MULT = 0.1						-- fuel consumption ratio while just existing
	NDefines.NMilitary.FUEL_EFFICIENCY_RAID_MULTIPLIER = 1.0			-- convoy raid multiplier for fuel sunk

	NDefines.NMilitary.OUT_OF_FUEL_EQUIPMENT_MULT = 0.05				-- ratio of the stats that you get from equipments that uses fuel and you lack it
	NDefines.NMilitary.OUT_OF_FUEL_SPEED_MULT = 0.4


	NDefines.NNavy.OUT_OF_FUEL_RANGE_FACTOR = -0.90